import type {
  Signal, ScannerResult, NewsEvent, Trade,
  PerformanceStats, TechnicalAnalysis, SMCAnalysis, MarketTicker
} from "./types";

// ── Market Ticker Data ──────────────────────────────────────
export const mockTickers: MarketTicker[] = [
  { symbol: "XAU/USD", price: 3382.45, change: 12.30, changePct: 0.36 },
  { symbol: "EUR/USD", price: 1.0845, change: -0.0023, changePct: -0.21 },
  { symbol: "GBP/USD", price: 1.2743, change: 0.0041, changePct: 0.32 },
  { symbol: "USD/JPY", price: 157.84, change: 0.52, changePct: 0.33 },
  { symbol: "BTC/USD", price: 68420.0, change: 1240.0, changePct: 1.85 },
  { symbol: "ETH/USD", price: 3890.50, change: 87.20, changePct: 2.29 },
  { symbol: "NASDAQ", price: 19847.30, change: 124.50, changePct: 0.63 },
  { symbol: "S&P500", price: 5612.80, change: 18.90, changePct: 0.34 },
  { symbol: "DXY", price: 103.24, change: -0.31, changePct: -0.30 },
  { symbol: "WTI/OIL", price: 78.42, change: -0.68, changePct: -0.86 },
];

// ── Active Signals ──────────────────────────────────────────
export const mockSignals: Signal[] = [
  {
    id: "sig-001",
    symbol: "XAU/USD",
    assetClass: "Gold",
    direction: "BUY",
    confidence: 91,
    entry: 3380.50,
    entryZone: [3378.00, 3383.00],
    stopLoss: 3373.80,
    takeProfits: [3388.00, 3395.00, 3404.50],
    riskReward: 2.8,
    probability: 88,
    timeframe: "M15",
    session: "London/NY Overlap",
    duration: "2-4 hours",
    createdAt: new Date(Date.now() - 1200000).toISOString(),
    status: "Active",
    reasoning: [
      "RSI Bullish Divergence on M15",
      "Bullish Order Block at 3378.00",
      "Liquidity Sweep Complete (Sell-Side Taken)",
      "DXY Showing Weakness (-0.30%)",
      "No High-Impact News in Next 2H",
      "VWAP Reclaim Confirmed",
      "EMA 20 Acting as Dynamic Support",
    ],
    technicalSummary: "RSI(14)=42 (recovering from oversold), MACD bullish cross forming on M15. Price reclaimed VWAP. EMA20/50 showing dynamic support. Momentum building.",
    fundamentalSummary: "USD weakness persists after dovish Fed commentary. Safe-haven demand elevated amid geopolitical tensions. Gold holding above key $3,370 institutional support.",
    newsSummary: "No high-impact USD or Gold-related news for next 4 hours. NFP scheduled Friday — increased uncertainty priced in.",
    institutionalFlow: "Net long institutional positioning on Gold per COT data. Smart money accumulation visible at 3370-3380 range. Sweep of retail sell stops at 3374 confirmed.",
    liquidityScore: 84,
    momentumScore: 72,
    trendStrength: 78,
    newsRisk: "Low",
  },
  {
    id: "sig-002",
    symbol: "EUR/USD",
    assetClass: "Forex",
    direction: "SELL",
    confidence: 87,
    entry: 1.0852,
    entryZone: [1.0848, 1.0858],
    stopLoss: 1.0872,
    takeProfits: [1.0830, 1.0810, 1.0790],
    riskReward: 3.1,
    probability: 83,
    timeframe: "H1",
    session: "London",
    duration: "4-8 hours",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    status: "Active",
    reasoning: [
      "Bearish Supply Zone Rejection at 1.0855",
      "Break of Structure (Bearish) on H1",
      "RSI Overbought (71) Divergence",
      "DXY Bullish Impulse Developing",
      "ECB Dovish Tone Yesterday",
      "Institutional Distribution Pattern",
    ],
    technicalSummary: "Price rejected from daily supply zone 1.0850-1.0860. BOS confirmed on H1. RSI(14)=71 showing divergence. MACD histogram declining.",
    fundamentalSummary: "ECB signaled potential rate cuts. EUR facing headwinds from weak PMI data. USD strength providing bearish pressure on EUR/USD.",
    newsSummary: "German CPI due in 3 hours — potential bearish catalyst. ECB speakers scheduled today.",
    institutionalFlow: "Institutional shorts accumulating. Large options expiry at 1.0800 this week. Net short EUR positioning per CFTC data.",
    liquidityScore: 79,
    momentumScore: 68,
    trendStrength: 72,
    newsRisk: "Medium",
  },
  {
    id: "sig-003",
    symbol: "BTC/USD",
    assetClass: "Crypto",
    direction: "BUY",
    confidence: 86,
    entry: 68100.0,
    entryZone: [67800.0, 68400.0],
    stopLoss: 66900.0,
    takeProfits: [69500.0, 71200.0, 73800.0],
    riskReward: 2.3,
    probability: 81,
    timeframe: "H4",
    session: "NY",
    duration: "1-3 days",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    status: "Active",
    reasoning: [
      "H4 Bullish Order Block at 67,800",
      "Fair Value Gap Fill Complete",
      "Change of Character (Bullish)",
      "Volume Spike Confirms Demand",
      "ETF Inflows Accelerating",
      "Market Structure Break Higher",
    ],
    technicalSummary: "CHoCH confirmed on H4. Price returned to fill FVG at 67,800-68,100. Strong volume on bounce. EMA21 reclaimed on daily.",
    fundamentalSummary: "Bitcoin ETF inflows resumed at $400M/day. Halving cycle historically bullish at this stage. Institutional accumulation confirmed.",
    newsSummary: "No major crypto-negative regulation news. Fed meeting minutes dovish — risk-on environment favorable.",
    institutionalFlow: "Whales accumulating 67K-68K range. Exchange outflows increasing (coins leaving exchanges to cold storage = bullish).",
    liquidityScore: 77,
    momentumScore: 81,
    trendStrength: 84,
    newsRisk: "Low",
  },
];

// ── Scanner Results ─────────────────────────────────────────
export const mockScannerResults: ScannerResult[] = [
  {
    symbol: "XAU/USD", name: "Gold", assetClass: "Gold",
    direction: "BUY", confidence: 91, entry: 3380.50,
    stopLoss: 3373.80, takeProfit: 3395.00, riskReward: 2.8,
    timeframe: "M15", session: "London/NY", reason: "OB + RSI Div + Liq Sweep",
    change24h: 0.36, volume: "High", lastScanned: "2 min ago"
  },
  {
    symbol: "EUR/USD", name: "Euro Dollar", assetClass: "Forex",
    direction: "SELL", confidence: 87, entry: 1.0852,
    stopLoss: 1.0872, takeProfit: 1.0810, riskReward: 3.1,
    timeframe: "H1", session: "London", reason: "Supply Zone + BOS",
    change24h: -0.21, volume: "High", lastScanned: "1 min ago"
  },
  {
    symbol: "BTC/USD", name: "Bitcoin", assetClass: "Crypto",
    direction: "BUY", confidence: 86, entry: 68100.0,
    stopLoss: 66900.0, takeProfit: 71200.0, riskReward: 2.3,
    timeframe: "H4", session: "NY", reason: "CHoCH + FVG + Volume",
    change24h: 1.85, volume: "High", lastScanned: "3 min ago"
  },
  {
    symbol: "GBP/USD", name: "Pound Dollar", assetClass: "Forex",
    direction: "BUY", confidence: 83, entry: 1.2738,
    stopLoss: 1.2710, takeProfit: 1.2790, riskReward: 2.0,
    timeframe: "M30", session: "London", reason: "Demand Zone + EMA Support",
    change24h: 0.32, volume: "Medium", lastScanned: "5 min ago"
  },
  {
    symbol: "NASDAQ", name: "NAS100", assetClass: "Index",
    direction: "BUY", confidence: 82, entry: 19840.0,
    stopLoss: 19720.0, takeProfit: 20050.0, riskReward: 1.75,
    timeframe: "H1", session: "NY", reason: "VWAP Support + Momentum",
    change24h: 0.63, volume: "High", lastScanned: "2 min ago"
  },
  {
    symbol: "ETH/USD", name: "Ethereum", assetClass: "Crypto",
    direction: "BUY", confidence: 80, entry: 3885.0,
    stopLoss: 3820.0, takeProfit: 4020.0, riskReward: 2.1,
    timeframe: "H4", session: "NY", reason: "Order Block + BTC Correlation",
    change24h: 2.29, volume: "High", lastScanned: "4 min ago"
  },
  {
    symbol: "USD/JPY", name: "Dollar Yen", assetClass: "Forex",
    direction: "SELL", confidence: 79, entry: 157.90,
    stopLoss: 158.40, takeProfit: 157.10, riskReward: 1.6,
    timeframe: "H1", session: "Tokyo", reason: "Supply Zone + BoJ Intervention Risk",
    change24h: 0.33, volume: "Medium", lastScanned: "6 min ago"
  },
  {
    symbol: "S&P500", name: "SPX500", assetClass: "Index",
    direction: "NEUTRAL", confidence: 60, entry: 5612.0,
    stopLoss: 5580.0, takeProfit: 5650.0, riskReward: 1.2,
    timeframe: "H4", session: "NY", reason: "Consolidation — Wait for Breakout",
    change24h: 0.34, volume: "Medium", lastScanned: "3 min ago"
  },
];

// ── Technical Analysis ──────────────────────────────────────
export const mockTechnicalAnalysis: TechnicalAnalysis = {
  symbol: "XAU/USD",
  timeframe: "M15",
  bias: "BUY",
  biasConfidence: 78,
  indicators: [
    { name: "RSI (14)", value: 42.3, signal: "BUY", strength: 65 },
    { name: "MACD", value: "Crossover", signal: "BUY", strength: 72 },
    { name: "Stochastic RSI", value: 28.4, signal: "BUY", strength: 80 },
    { name: "CCI (20)", value: -85.2, signal: "BUY", strength: 70 },
    { name: "ATR (14)", value: 6.84, signal: "NEUTRAL", strength: 50 },
    { name: "ADX (14)", value: 28.6, signal: "BUY", strength: 65 },
    { name: "OBV", value: "Rising", signal: "BUY", strength: 74 },
    { name: "VWAP", value: 3379.20, signal: "BUY", strength: 68 },
  ],
  oscillators: [
    { name: "RSI (14)", value: 42.3, signal: "BUY", strength: 65 },
    { name: "MACD", value: "Crossover", signal: "BUY", strength: 72 },
    { name: "Stochastic RSI", value: 28.4, signal: "BUY", strength: 80 },
    { name: "CCI (20)", value: -85.2, signal: "BUY", strength: 70 },
    { name: "Momentum (10)", value: 8.4, signal: "BUY", strength: 60 },
  ],
  movingAverages: [
    { name: "EMA 20", value: 3378.10, signal: "BUY", strength: 70 },
    { name: "EMA 50", value: 3372.40, signal: "BUY", strength: 75 },
    { name: "EMA 200", value: 3340.80, signal: "BUY", strength: 90 },
    { name: "SMA 20", value: 3376.50, signal: "BUY", strength: 65 },
    { name: "SMA 50", value: 3369.80, signal: "BUY", strength: 72 },
    { name: "VWAP", value: 3379.20, signal: "BUY", strength: 68 },
    { name: "Ichimoku Cloud", value: "Above Cloud", signal: "BUY", strength: 80 },
    { name: "SuperTrend", value: 3371.20, signal: "BUY", strength: 78 },
    { name: "Parabolic SAR", value: 3370.40, signal: "BUY", strength: 72 },
    { name: "Bollinger Bands", value: "Lower Band", signal: "BUY", strength: 68 },
  ],
  summary: { buy: 16, sell: 2, neutral: 4 },
  updatedAt: new Date().toISOString(),
};

// ── SMC Analysis ────────────────────────────────────────────
export const mockSMCAnalysis: SMCAnalysis = {
  symbol: "XAU/USD",
  marketStructure: "Bullish",
  trend: "Uptrend",
  premium: 3395.00,
  discount: 3360.00,
  equilibrium: 3377.50,
  currentPosition: "Discount",
  institutionalBias: "Accumulation",
  liquiditySweep: true,
  sweepDirection: "Bullish",
  levels: [
    { type: "OrderBlock", direction: "Bullish", price: 3378.00, strength: "Strong", status: "Active", timeframe: "M15" },
    { type: "FVG", direction: "Bullish", price: 3374.50, strength: "Medium", status: "Active", timeframe: "M15" },
    { type: "DemandZone", direction: "Bullish", price: 3370.00, strength: "Strong", status: "Active", timeframe: "H1" },
    { type: "LiquidityZone", direction: "Bearish", price: 3390.00, strength: "Strong", status: "Active", timeframe: "H1" },
    { type: "BreakOfStructure", direction: "Bullish", price: 3384.00, strength: "Medium", status: "Active", timeframe: "M15" },
    { type: "SupplyZone", direction: "Bearish", price: 3400.00, strength: "Strong", status: "Active", timeframe: "H4" },
    { type: "ChangeOfCharacter", direction: "Bullish", price: 3376.50, strength: "Strong", status: "Active", timeframe: "M15" },
    { type: "MitigationBlock", direction: "Bullish", price: 3365.00, strength: "Medium", status: "Mitigated", timeframe: "H1" },
  ],
};

// ── News Events ─────────────────────────────────────────────
export const mockNewsEvents: NewsEvent[] = [
  {
    id: "news-001",
    title: "Fed Chair Powell Speaks",
    currency: "USD",
    impact: "High",
    actual: null,
    forecast: "Hawkish",
    previous: "Neutral",
    time: "14:30",
    date: "Today",
    aiBias: "Bearish",
    volatilityExpected: "High",
    fakeMoveRisk: 72,
    waitTime: "15 min after",
  },
  {
    id: "news-002",
    title: "US Core CPI (MoM)",
    currency: "USD",
    impact: "High",
    actual: "0.3%",
    forecast: "0.3%",
    previous: "0.4%",
    time: "12:30",
    date: "Today",
    aiBias: "Neutral",
    volatilityExpected: "Medium",
    fakeMoveRisk: 45,
    waitTime: "5 min after",
  },
  {
    id: "news-003",
    title: "ECB Rate Decision",
    currency: "EUR",
    impact: "High",
    actual: null,
    forecast: "4.25%",
    previous: "4.50%",
    time: "13:15",
    date: "Tomorrow",
    aiBias: "Bearish",
    volatilityExpected: "High",
    fakeMoveRisk: 65,
    waitTime: "30 min after",
  },
  {
    id: "news-004",
    title: "UK GDP (QoQ)",
    currency: "GBP",
    impact: "Medium",
    actual: null,
    forecast: "0.2%",
    previous: "0.1%",
    time: "07:00",
    date: "Tomorrow",
    aiBias: "Bullish",
    volatilityExpected: "Medium",
    fakeMoveRisk: 38,
    waitTime: "5 min after",
  },
  {
    id: "news-005",
    title: "BOJ Interest Rate Decision",
    currency: "JPY",
    impact: "High",
    actual: null,
    forecast: "0.25%",
    previous: "0.10%",
    time: "03:00",
    date: "Friday",
    aiBias: "Bullish",
    volatilityExpected: "High",
    fakeMoveRisk: 80,
    waitTime: "30 min after",
  },
  {
    id: "news-006",
    title: "US NFP (Non-Farm Payrolls)",
    currency: "USD",
    impact: "High",
    actual: null,
    forecast: "185K",
    previous: "206K",
    time: "12:30",
    date: "Friday",
    aiBias: "Neutral",
    volatilityExpected: "High",
    fakeMoveRisk: 85,
    waitTime: "20 min after",
  },
];

// ── Recent Trades ────────────────────────────────────────────
export const mockTrades: Trade[] = [
  {
    id: "trade-001", symbol: "XAU/USD", direction: "BUY",
    entry: 3361.20, exit: 3378.40, stopLoss: 3354.00, takeProfit: 3380.00,
    lots: 0.1, profit: 171.00, status: "Closed",
    openedAt: "2026-06-25T09:30:00Z", closedAt: "2026-06-25T13:15:00Z",
    timeframe: "M15", signalConfidence: 89, pnlPips: 171,
  },
  {
    id: "trade-002", symbol: "EUR/USD", direction: "SELL",
    entry: 1.0871, exit: 1.0840, stopLoss: 1.0890, takeProfit: 1.0840,
    lots: 0.5, profit: 155.00, status: "Closed",
    openedAt: "2026-06-25T14:00:00Z", closedAt: "2026-06-25T18:30:00Z",
    timeframe: "H1", signalConfidence: 85, pnlPips: 31,
  },
  {
    id: "trade-003", symbol: "BTC/USD", direction: "BUY",
    entry: 67200.0, stopLoss: 65800.0, takeProfit: 71000.0,
    lots: 0.01, status: "Active",
    openedAt: "2026-06-26T02:00:00Z",
    timeframe: "H4", signalConfidence: 86,
  },
  {
    id: "trade-004", symbol: "GBP/USD", direction: "BUY",
    entry: 1.2710, exit: 1.2690, stopLoss: 1.2690, takeProfit: 1.2760,
    lots: 0.3, profit: -60.00, status: "Closed",
    openedAt: "2026-06-24T10:00:00Z", closedAt: "2026-06-24T11:30:00Z",
    timeframe: "M30", signalConfidence: 78, pnlPips: -20,
  },
  {
    id: "trade-005", symbol: "NASDAQ", direction: "BUY",
    entry: 19720.0, exit: 19850.0, stopLoss: 19640.0, takeProfit: 19900.0,
    lots: 1, profit: 130.00, status: "Closed",
    openedAt: "2026-06-23T15:00:00Z", closedAt: "2026-06-23T20:00:00Z",
    timeframe: "H1", signalConfidence: 82, pnlPips: 130,
  },
];

// ── Performance Stats ───────────────────────────────────────
export const mockPerformance: PerformanceStats = {
  totalTrades: 127,
  winRate: 73.2,
  avgRR: 2.4,
  totalProfit: 8420.50,
  todayProfit: 326.00,
  weeklyProfit: 1284.50,
  monthlyProfit: 3847.20,
  maxDrawdown: 4.8,
  sharpeRatio: 2.31,
  profitFactor: 2.78,
  consecutiveWins: 8,
  consecutiveLosses: 0,
};

// ── Chart Performance Data ──────────────────────────────────
export const mockChartData = [
  { date: "Jun 1", equity: 10000, pnl: 0 },
  { date: "Jun 3", equity: 10280, pnl: 280 },
  { date: "Jun 5", equity: 10540, pnl: 540 },
  { date: "Jun 7", equity: 10380, pnl: 380 },
  { date: "Jun 9", equity: 10720, pnl: 720 },
  { date: "Jun 11", equity: 11050, pnl: 1050 },
  { date: "Jun 13", equity: 10890, pnl: 890 },
  { date: "Jun 15", equity: 11240, pnl: 1240 },
  { date: "Jun 17", equity: 11680, pnl: 1680 },
  { date: "Jun 19", equity: 11920, pnl: 1920 },
  { date: "Jun 21", equity: 12340, pnl: 2340 },
  { date: "Jun 23", equity: 12100, pnl: 2100 },
  { date: "Jun 24", equity: 12650, pnl: 2650 },
  { date: "Jun 25", equity: 13080, pnl: 3080 },
  { date: "Jun 26", equity: 13420, pnl: 3420 },
];

// ── Assets List ─────────────────────────────────────────────
export const ASSETS = [
  { symbol: "XAUUSD", name: "Gold (XAU/USD)", class: "Gold", tv: "TVC:GOLD" },
  { symbol: "EURUSD", name: "EUR/USD", class: "Forex", tv: "FX:EURUSD" },
  { symbol: "GBPUSD", name: "GBP/USD", class: "Forex", tv: "FX:GBPUSD" },
  { symbol: "USDJPY", name: "USD/JPY", class: "Forex", tv: "FX:USDJPY" },
  { symbol: "AUDUSD", name: "AUD/USD", class: "Forex", tv: "FX:AUDUSD" },
  { symbol: "USDCAD", name: "USD/CAD", class: "Forex", tv: "FX:USDCAD" },
  { symbol: "NASDAQ", name: "NASDAQ 100", class: "Index", tv: "NASDAQ:NDX" },
  { symbol: "SPX500", name: "S&P 500", class: "Index", tv: "CBOE:SPX" },
  { symbol: "BTCUSD", name: "Bitcoin", class: "Crypto", tv: "BITSTAMP:BTCUSD" },
  { symbol: "ETHUSD", name: "Ethereum", class: "Crypto", tv: "BITSTAMP:ETHUSD" },
  { symbol: "AAPL", name: "Apple Inc.", class: "Stock", tv: "NASDAQ:AAPL" },
  { symbol: "TSLA", name: "Tesla Inc.", class: "Stock", tv: "NASDAQ:TSLA" },
  { symbol: "NVDA", name: "NVIDIA Corp.", class: "Stock", tv: "NASDAQ:NVDA" },
  { symbol: "XAGUSD", name: "Silver (XAG/USD)", class: "Commodity", tv: "TVC:SILVER" },
  { symbol: "USOIL", name: "WTI Crude Oil", class: "Commodity", tv: "TVC:USOIL" },
] as const;
